
public enum Operand {
	PLUS, MINUS, MULT, DIV, POW, 
	SQRT, CBRT, LOG, NLOG, NEG, ABS, 
	SIN, COS, TAN, SEC, CSC, COT,
	ARCSIN, ARCCOS, ARCTAN, ARCSEC, ARCCSC, ARCCOT,
	INDEP_VAR, CONSTANT, CONST_E, CONST_PI, OP, CP
}
